nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: btungut/hand-drill
  pullPolicy: IfNotPresent
  tag: "0.0.2"

resources:
  limits:
    cpu: 100m
    memory: 128Mi

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
