apiVersion: v1
kind: Pod
metadata:
  name: hand-drill
spec:
  containers:
  - name: hand-drill
    image: btungut/hand-drill:0.3
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
    ports:
      - name: http
        containerPort: 80
      - name: iperf3
        containerPort: 5201
