apiVersion: v1
kind: Pod
metadata:
  name: hand-drill
  labels:
    app: hand-drill
spec:
  containers:
  - name: hand-drill
    image: btungut/hand-drill:0.3
    ports:
      - name: http
        containerPort: 80
      - name: iperf3
        containerPort: 5201
---
kind: Service
apiVersion: v1
metadata:
  name: hand-drill
spec:
  selector:
    app: hand-drill
  type:  NodePort
  ports:
  - name: http
    port:  8080
    targetPort: http
  - name: iperf3
    port:  5201
    targetPort: iperf3