name: balpine CI

on:
  push:
    tags:
      - "v*"
    paths:
      - "balpine/**"

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - id: env
        run: |
          TAG=$(echo ${GITHUB_REF_NAME#v})
          echo "tag = $TAG"
          echo "##[set-output name=tag;]$TAG"

      - run: |
          echo "sonuc : btungut/fluentd-kube-elastic:${{ steps.env.outputs.tag }}"

      # - uses: actions/checkout@v3
      # - name: build
      #   run: docker build . -t btungut/balpine:$(date +%s)
      #   working-directory: balpine